blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import home, about, test, post, skill_detail, skill_search

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('test/', test, name='test'),
    path('post/', post, name='post'),
    path('skill_detail/<cod>', skill_detail, name='skill_detail'),
    path('skill_search/', skill_search, name='skill_search'),
]

core/models.py
from django.db import models


# Create your models here.
class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    descripcion = models.TextField(blank=True, null=True)
    avatar = models.ImageField(upload_to='persona/avatar', blank=True, null=True)
    whatsapp = models.CharField(max_length=15, blank=True, null=True)
    correo = models.EmailField(blank=True, null=True, unique=True)
    pdf = models.FileField(upload_to='persona/pdf', blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)

    class Meta:
        verbose_name_plural = 'Persona'
        ordering = ['-apellido']
        # Modifica el nombre de la TABLA en la DB
        # db_table = 'Persona'


class Skills(models.Model):
    codigo = models.CharField(max_length=8, primary_key=True)
    skill = models.CharField(max_length=150)
    nivel = models.IntegerField()
    estado = models.BooleanField(default=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, blank=True, null=True)
    imagen = models.CharField(max_length=350, null=True, blank=True)
    descripcion = models.TextField(blank=True, null=True)
    video = models.CharField(max_length=350, null=True, blank=True)

    def __str__(self):
        return '({}) {}'.format(self.codigo, self.skill)

    class Meta:
        verbose_name_plural = 'Skill'
        ordering = ['skill']


class Post(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha = models.DateTimeField()
    imagen = models.CharField(max_length=350, null=True, blank=True)
    estado = models.BooleanField(default=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name_plural = 'Post'
        ordering = ['fecha']

core/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Persona, Skills, Post
from django.core.paginator import Paginator


# Create your views here.
def home(request):
    template_name = 'index.html'
    # Este objeto almacenará toda la información de la persona
    persona = Persona.objects.get(id=1)
    # Este objeto almacenará sus SKILLS o HABILIDADES
    # 100 objetos
    skills = Skills.objects.all()
    # Dividimos los objetos de 3 en 3
    paginator = Paginator(skills,3)
    # Devolver el número de página en el que me encuentro
    page_number = request.GET.get('page')
    # Y devolver los objetos de esa página
    skills = paginator.get_page(page_number)
    context = {
        'per': persona, 'ski': skills
    }
    return render(request, template_name, context)


def about(request):
    template_name = 'about.html'
    # Este objeto almacenará toda la información de la persona
    persona = Persona.objects.get(id=1)
    context = {
        'per': persona
    }
    return render(request, template_name, context)


def post(request):
    template_name = 'post.html'
    persona = Persona.objects.get(id=1)
    post = Post.objects.all()
    context = {
        'per': persona, 'pos': post
    }
    return render(request, template_name, context)


def skill_detail(request, cod):
    template_name = 'skill_detail.html'
    persona = Persona.objects.get(id=1)
    try:
        skilldetail = Skills.objects.get(codigo=cod)
    except Skills.DoesNotExist:
        raise Http404("Skill No Existe")
    context = {
        'per': persona, 'ski': skilldetail
    }
    return render(request, template_name, context)


def skill_search(request):
    template_name = 'index.html'
    q = request.GET["q"]
    # Cuando deseamos mostrar varias coincidencias de busqueda usamos FILTER
    skills = Skills.objects.filter(estado=True, skill__icontains=q)
    # select * from skills where skill like '%q%'
    persona = Persona.objects.get(id=1)

    context = {
        'per': persona, 'ski': skills
    }
    return render(request, template_name, context)


def test(request):
    template_name = 'test.html'
    return render(request, template_name)

core/templates/about.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
    
    <div class="main-wrapper">
	    	    
	    <article class="about-section py-5">
		    <div class="container">
			    <h2 class="title mb-3">About Me</h2>
			    
			    <p>{{ per.descripcion }}</p>
			    <figure><img class="img-fluid" src={{ per.avatar.url }} alt="image"></figure>

			    <h5 class="mt-5">My Skills and Experiences</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    <h5 class="mt-5">Side Projects</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    
			    <figure><a href="https://made4dev.com"><img class="img-fluid" src="{% static 'assets/images/promo-banner.jpg' %}" alt="image"></a></figure>
		    </div>
	    </article><!--//about-section-->
	    
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center">
			    <h2 class="heading">Newsletter</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <form class="signup-form form-inline justify-content-center pt-3">
                    <div class="form-group">
                        <label class="sr-only" for="semail">Your email</label>
                        <input type="email" id="semail" name="semail1" class="form-control mr-md-1 semail" placeholder="Enter email">
                    </div>
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                </form>
		    </div><!--//container-->
	    </section>
    </div><!--//main-wrapper-->

{% endblock %}

core/templates/base/base.html
{%load static%}
<html lang="en">
<head>
    <title>My Blog Person</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Gian PC">
    <link rel="shortcut icon" href="favicon.ico">

    <!-- FontAwesome JS-->
	<script defer src="{% static 'assets/fontawesome/js/all.min.js' %}"></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %}">

</head>

<body>

    <header class="header text-center">
	    <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">{{ per.nombre }} Blog</a></h1>

	    <nav class="navbar navbar-expand-lg navbar-dark" >

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src={{ per.avatar.url }} alt="image" >

					<div class="bio mb-3">{{ per.descripcion|truncatechars:100 }}<br><a href="{% url 'core:about' %}">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr>
				</div><!--//profile-section-->

				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item active">
					    <a class="nav-link" href="{% url 'core:home' %}"><i class="fas fa-home fa-fw mr-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="{% url 'core:post' %}"><i class="fas fa-bookmark fa-fw mr-2"></i>Blog Post</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="{% url 'core:about' %}"><i class="fas fa-user fa-fw mr-2"></i>About Me</a>
					</li>
				</ul>

				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="{{ per.pdf.url }}" target="_blank">My CV</a>
				</div>
			</div>
		</nav>
    </header>

    {% block content %}

    {% endblock %}

	<footer class="footer text-center py-2 theme-bg-dark">

	        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="http://google.com" target="_blank">{{ per.nombre }}</a> for developers</small>

	</footer>






    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->
    <div id="config-panel" class="config-panel d-none d-lg-block">
        <div class="panel-inner">
            <a id="config-trigger" class="config-trigger config-panel-hide text-center" href="#"><i class="fas fa-cog fa-spin mx-auto" data-fa-transform="down-6" ></i></a>
            <h5 class="panel-title">Choose Colour</h5>
            <ul id="color-options" class="list-inline mb-0">
                <li class="theme-1 active list-inline-item"><a data-style="{% static 'assets/css/theme-1.css' %}" href="#"></a></li>
                <li class="theme-2  list-inline-item"><a data-style="{% static 'assets/css/theme-2.css' %}" href="#"></a></li>
                <li class="theme-3  list-inline-item"><a data-style="{% static 'assets/css/theme-3.css' %}" href="#"></a></li>
                <li class="theme-4  list-inline-item"><a data-style="{% static 'assets/css/theme-4.css' %}" href="#"></a></li>
                <li class="theme-5  list-inline-item"><a data-style="{% static 'assets/css/theme-5.css' %}" href="#"></a></li>
                <li class="theme-6  list-inline-item"><a data-style="{% static 'assets/css/theme-6.css' %}" href="#"></a></li>
                <li class="theme-7  list-inline-item"><a data-style="{% static 'assets/css/theme-7.css' %}" href="#"></a></li>
                <li class="theme-8  list-inline-item"><a data-style="{% static 'assets/css/theme-8.css' %}" href="#"></a></li>
            </ul>
            <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
        </div><!--//panel-inner-->
    </div><!--//configure-panel-->



    <!-- Javascript -->
    <script src="{% static 'assets/plugins/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'assets/js/demo/style-switcher.js' %}"></script>


</body>
</html>

core/templates/index.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
    
    <div class="main-wrapper">
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center">
			    <h2 class="heading">The Skills</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <form class="signup-form form-inline justify-content-center pt-3" action="{% url 'core:skill_search'  %}">
                    <div class="form-group">
                        <input class="form-control mr-sm-2"   name="q" type="search" placeholder="Search" aria-label="Search">
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
		    </div><!--//container-->
	    </section>
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container">

                {% for item in ski %}
			    <div class="item mb-5">
				    <div class="media">
					    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src={{ item.imagen }} alt="image">
					    <div class="media-body">
						    <h3 class="title mb-1"><a href="{% url 'core:skill_detail' item.codigo %}">{{item.skill}}</a></h3>

                            {% with ''|center:item.nivel as cantidad %}
                                {% for _ in cantidad %}
                                    {{ '⭐' }}
                                {% endfor %}
                            {% endwith %}

						    <div class="intro"><p align="justify"> {{ item.descripcion|truncatechars:250 }}</p></div>
						    <a class="more-link" href="{% url 'core:skill_detail' item.codigo %}">Leer Más &rarr;</a>
					    </div><!--//media-body-->
				    </div><!--//media-->
			    </div><!--//item-->

                {% empty %}
                    <h2>No hay Skills que mostrar</h2>
                {% endfor %}


            {% if ski|length > 0 %}
                {% if ski.has_next %}
                    <nav class="blog-nav nav nav-justified my-5">

                      <a class="nav-link-next nav-item nav-link rounded" href="?page={{ ski.next_page_number }}">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
                    </nav>
                {% endif %}

                {% if ski.has_previous %}
                    <nav class="blog-nav nav nav-justified my-5">

                      <a class="nav-link-next nav-item nav-link rounded" href="?page={{ ski.previous_page_number }}">Previous<i class="arrow-next fas fa-long-arrow-alt-left"></i></a>
                    </nav>
                {% endif %}

            {% endif %}

				
		    </div>
	    </section>
	</div>
{% endblock %}

core/templates/post.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
    
    <div class="main-wrapper">
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container">
				<h2 class="title mb-3">Read Posts</h2>
                {% for item in pos %}
			    <div class="item mb-5">
				    <div class="media">
					    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src={{ item.imagen }} alt="image">
					    <div class="media-body">
						    <h3 class="title mb-1"><a href="blog-post.html">{{ item.titulo }}</a></h3>
						    <div class="meta mb-1"><span class="date">Publicado</span><span class="time">{{ item.fecha }}</span><span class="comment"><a href="#">4 comments</a></span></div>
						    <div class="intro">{{ item.descripcion|truncatechars:200 }}</div>
						    <a class="more-link" href="blog-post.html">Leer más</a>
					    </div><!--//media-body-->
				    </div><!--//media-->
			    </div><!--//item-->
                {% endfor %}

			    
			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded-right" href="#">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>
				
		    </div>
	    </section>
    </div><!--//main-wrapper-->
{% endblock %}

core/templates/skill_detail.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
    <div class="main-wrapper">
    <article class="about-section py-5">
    <div class="container">
        <h3 class="mt-5 mb-3">{{ski.skill}}</h3>
        <p>{{ ski.descripcion }}</p>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe width="560" height="315" src={{ ski.video }} frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
        </article>
    </div>
{% endblock %}

core/templates/test.html
{% extends 'base/base.html' %}
{% block content %}
<h1> Pruebaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa </h1>
{% endblock %}